# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd5f2d1029364e484e08bf25dcb488e5717ad6796ac38bfc97e9981449c423bfb9bbb18bcadc507643a6c9ef62fe9f556b1f5cd9122f587e6645f22a6e606a0

test:
  secret_key_base: 0bd696601124a1169e140014e70c5941e304a1a07d22344fde3dc7c355b557dc56023fb9007474775c8bfc36beafdbeab2000df1070130175fcf76d4c69c7eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
